### ISSUE TITLE
Missing a big amount of memes

### ISSUE THREAD

**Issue by rikiless** [fprochazka/memes#4]
http://www.rikiho.net/memes.zip

:)

**Comment by fprochazka** [comment]
Lenoch líná! :)

**Comment by fprochazka** [comment]
Podstatou není mít všechny, ale takové, které často někomu chceš posílat. A ten tvůj archiv se mi fakt třídit nechce :) 

Kdybys byl hodně hodnej, tak bys mohl pár zajímavých vybrat a poslat pull. Když je přebereš, tak si je klidně i sám commitnu. 

Ale nechci moc variant od jednoho, jenom nějakou nejznámější a ideálně s textem, aby byla jasnější pro lidi, co to neznají :)

Každopádně díky, že ses namáhal :)

**Comment by rikiless** [comment]
ok, postnu ti nejake moje oblubene :)

**Comment by fprochazka** [comment]
Díky! :)
